#pragma once
//#define _WIN32_WINNT  0x0601
#include <sdkddkver.h>
#include "dxgidebug.h"
//#define NOGDICAPMASKS
//#define NOVIRTUALKEYCODES
//#define NOWINMESSAGES
//#define NOWINSTYLES
//#define NOSYSMETRICS
//#define NOMENUS
//#define NOICONS
//#define NOKEYSTATES
//#define NOSYSCOMMANDS
//#define NORASTEROPS
////#define NOSHOWWINDOW
//#define OEMRESOURCE
//#define NOATOM
//#define NOCLIPBOARD
//#define NOCOLOR
//#define NOCTLMGR
//#define NODRAWTEXT
//#define NOGDI
//#define NOKERNEL
////#define NOUSER
//#define NONLS
//#define NOMB
//#define NOMEMMGR
//#define NOMETAFILE
//#define NOMINMAX
////#define NOMSG
//#define NOOPENFILE
//#define NOSCROLL
//#define NOSERVICE
//#define NOSOUND
//#define NOTEXTMETRIC
//#define NOWH
//#define NOWINOFFSETS
//#define NOCOMM
//#define NOKANJI
//#define NOHELP
//#define NOPROFILER
//#define NODEFERWINDOWPOS
//#define NOMCX

#include <Windows.h>
#include <wrl/client.h>
namespace wrl = Microsoft::WRL;